### PR TITLE
zzz: new package at 1?

### PR DESCRIPTION
**Pull request by eudaldgr**
## Description of package

I don't know if this is the place where I should publish it, but there it goes.

## Installed manifest of package
```
/var/db/kiss/installed/zzz/version
/var/db/kiss/installed/zzz/sources
/var/db/kiss/installed/zzz/manifest
/var/db/kiss/installed/zzz/files/zzz.8
/var/db/kiss/installed/zzz/files/zzz
/var/db/kiss/installed/zzz/files/
/var/db/kiss/installed/zzz/depends
/var/db/kiss/installed/zzz/checksums
/var/db/kiss/installed/zzz/build
/var/db/kiss/installed/zzz/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/zzz.8
/usr/share/man/man8/
/usr/share/man/
/usr/share/
/usr/bin/zzz
/usr/bin/ZZZ
/usr/bin/
/usr/
```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify @dylanaraps if I can no longer maintain this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
I don't think I'll accept this unless the sources point to a release of some kind. What happens if you need to make frequent changes to `zzz`? Each bug fix (or change) will require a PR/bump here.

**Comment by konimex** [comment]
This `zzz` is part of Void's initscripts
https://github.com/void-linux/void-runit

**Comment by dylanaraps** [comment]
Ah. And it's had no changes in 3 years. I'm OK with this now.

**Comment by eudaldgr** [comment]
It's OK to have here without external sources? Or it's better to put inside the [init repo](https://github.com/kisslinux/init)?

**Pull request merged**
