### PR TITLE
netsurf-fb: fix checksums for xxd

### PR DESCRIPTION
**Pull request by sdsddsd1**
```
No manifest change
```

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
You may want to pin the xxd link to a specific commit like so: https://raw.githubusercontent.com/vim/vim/363d6148dfc2cc17fb0d286c7a36c305f56f5813/src/xxd/xxd.c

This will prevent upstream changes from breaking checksums here.

**Comment by dylanaraps** [comment]
Oh, you've already pinned the sources to a tag I see. Never mind then!

**Comment by konimex** [comment]
Doesn't busybox have an xxd implementation so pulling in xxd from vim won't be necessary?

On 9 July 2020 8:22:34 pm GMT+07:00, dylan <notifications@github.com> wrote:
>You may want to pin the xxd link to a specific commit like so:
>https://raw.githubusercontent.com/vim/vim/363d6148dfc2cc17fb0d286c7a36c305f56f5813/src/xxd/xxd.c
>
>This will prevent upstream changes from breaking checksums here.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kisslinux/community/pull/1011#issuecomment-656124158

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdsddsd1** [comment]
On a first try, busybox xxd is sadly not sufficent.

**Pull request merged**
