### PR TITLE
youtube-dl: update checksum (bis)

### PR DESCRIPTION
**Pull request by Vouivre**
## Existing package

- [x] I am the maintainer of this package.

If there is the same problem as PR https://github.com/kisslinux/community/pull/1443, just tell me what is wrong. I have 
installed this version and I didn't see which file were installed on `/`.

Thanks!

### CODE REVIEW

**Comment by dylanaraps** [comment]
See how it creates `community/version` instead of modifying `community/community/youtube-dl/version`? https://github.com/Vouivre/community/blob/c81530e634764cf6f7d7d81fa5ce1e0ad25646c3/version

**Comment by onodera-punpun** [comment]
I'm still having a checksum mismatch...

**Comment by dylanaraps** [comment]
Looks like we'll need to find a mirror.

**Comment by Vouivre** [comment]
Here perhaps:

https://yt-dl.org/download.html

Do I update this package with this sources ? 

Perhaps we could also drop it to use an alternative. I will probably open a subject on the KISS Linux community on Reddit.

**Pull request merged**
