### PR TITLE
dbus: new package at 1.12.16

### PR DESCRIPTION
**Pull request by alaughlin**
## Description of package
people keep asking about dbus so here it is 😛 

## Checklist

- [x] Latest upstream version.
- [x] I agree to maintain this package (**required**).
- [x] I agree to notify KISS if I can no longer maintain this package (**required**).

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the PR, however `dbus` won't be added to Community. Instead, it can live in a 3rd-party repository as I'd like to keep Community somewhat in line with the offerings in the official repositories. :+1:

**Comment by alaughlin** [comment]
No worries!

**Comment by scsijon** [comment]
On 19/11/19 01:02, dylan wrote:
> Thanks for the PR, however `dbus` won't be added to Community. Instead, it can live in a 3rd-party repository as I'd like to keep Community somewhat in line with the offerings in the official repositories. :+1:
> 
> 
> 
  Just a thought if I may add as this is the first time i've come across 
this problem.

This third party repository should be ?where on github? and linked to 
the KISS project. It really should still be somewhere others can see and 
use. We shouldn't want work to be duplicated by a nunber of people as 
the kiss package lists build up. And how it's managed could/would be up 
to those submitters rather than Dylan as he has enough on his hands with 
the main KISS work he has to do.

**Comment by konimex** [comment]
> Just a thought if I may add as this is the first time i've come across this problem. This third party repository should be ?where on github?

Just create your own GitHub repo.

>where on github? and linked to the KISS project. It really should still be somewhere others can see and use.

Add it to the topic kiss-repo (https://github.com/topics/kiss-repo).

**Comment by scsijon** [comment]
On 19/11/19 08:27, M. Herdiansyah wrote:
>> Just a thought if I may add as this is the first time i've come across this problem. This third party repository should be ?where on github?
> 
> Just create your own GitHub repo.
> 
>> where on github? and linked to the KISS project. It really should still be somewhere others can see and use.
> 
> Add it to the topic kiss-repo (https://github.com/topics/kiss-repo).
> 
thankyou

**Pull request closed without merging**
