### PR TITLE
Various packages: adoption (#415)

### PR DESCRIPTION
**Pull request by IslandAlpha**
Adopting netsurf, perl-html-parser, and perl-html-tags.

Changing email on apulse and qrencode.

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify @dylanaraps if I can no longer maintain this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Is there any purpose to `apulse` if you don't mind me asking? None of the packages in the repositories require it no?

**Comment by IslandAlpha** [comment]
I added it for firefox since it only supports pulseaudio

**Comment by dylanaraps** [comment]
No no. Our Firefox works with ALSA. There's no need for apulse or pulseaudio. In reality, Mozilla just compile their Firefox builds with `--disable-alsa`.

**Comment by IslandAlpha** [comment]
So they do `--disable-alsa` and tell everyone they need to use poetterware for audio? Wow.

In that case there's no need for `apulse`, lets get rid of it

**Comment by dylanaraps** [comment]
Pretty much. They say they won't maintain it in the codebase anymore though I haven't seen any movement over the years to remove the code itself.

Awesome. Shall I remove it for you?

**Comment by IslandAlpha** [comment]
Go ahead

**Pull request merged**
