### PR TITLE
gmp: new package at 6.2.0

### PR DESCRIPTION
**Pull request by eudaldgr**
## Description of package

[The GNU Multiple Precision Arithmetic Library](https://gmplib.org/)

## Installed manifest of package

```
/var/db/kiss/installed/gmp/version
/var/db/kiss/installed/gmp/sources
/var/db/kiss/installed/gmp/manifest
/var/db/kiss/installed/gmp/checksums
/var/db/kiss/installed/gmp/build
/var/db/kiss/installed/gmp/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/info/gmp.info-2
/usr/share/info/gmp.info-1
/usr/share/info/gmp.info
/usr/share/info/
/usr/share/
/usr/lib/pkgconfig/gmp.pc
/usr/lib/pkgconfig/
/usr/lib/libgmp.so.10.4.0
/usr/lib/libgmp.so.10
/usr/lib/libgmp.so
/usr/lib/libgmp.la
/usr/lib/libgmp.a
/usr/lib/
/usr/include/gmp.h
/usr/include/
/usr/
```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify @dylanaraps if I can no longer maintain this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
The depends file can be removed if it is empty. 

What are you packaging exactly?

**Comment by eudaldgr** [comment]
Sorry for the empty file..
I will package this [ledger-cli](https://github.com/ledger/ledger)

**Comment by dylanaraps** [comment]
Other distributions have different dependencies: https://www.archlinux.org/packages/community/x86_64/ledger/

**Comment by eudaldgr** [comment]
I haven't see the other distributions i will try to package with others. If this packages are not accepted on the community repo i will remove the PR.

**Comment by dylanaraps** [comment]
The dependencies for ledger are:

```
boost
cmake make
mpfr  make
```

With `mpfr` depending on `gmp`.

This is my ledger build file:

```
#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DCMAKE_INSTALL_LIBDIR:PATH=lib \
    -DUSE_PYTHON:BOOL=FALSE \
    -DBoost_USE_STATIC_LIBS=ON

cmake --build   build
cmake --install build
```

**Comment by dylanaraps** [comment]
I will maintain `mpfr` and `gmp`. :+1:

**Comment by eudaldgr** [comment]
And now?
I delete `utfcpp` `mpfr` `gmp` PR?

**Comment by dylanaraps** [comment]
Keep the `utfcpp` one open for now. The other two can be closed, yes!

**Pull request closed without merging**
