### PR TITLE
ghostscript: new package at version 9.52

### PR DESCRIPTION
**Pull request by Vouivre**
## Description of package

An interpreter for the PostScript language.

## Installed manifest of package

(`cat /var/db/kiss/installed/<pkg_name>/manifest`)

```
/var/db/kiss/installed/ghostscript/version
/var/db/kiss/installed/ghostscript/sources
/var/db/kiss/installed/ghostscript/manifest
/var/db/kiss/installed/ghostscript/depends
/var/db/kiss/installed/ghostscript/checksums
/var/db/kiss/installed/ghostscript/build
/var/db/kiss/installed/ghostscript/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man1/ps2ps.1
/usr/share/man/man1/ps2pdfwr.1
/usr/share/man/man1/ps2pdf14.1
/usr/share/man/man1/ps2pdf13.1
/usr/share/man/man1/ps2pdf12.1
/usr/share/man/man1/ps2pdf.1
/usr/share/man/man1/ps2epsi.1
/usr/share/man/man1/ps2ascii.1
/usr/share/man/man1/printafm.1
/usr/share/man/man1/pfbtopfa.1
/usr/share/man/man1/pf2afm.1
/usr/share/man/man1/pdf2ps.1
/usr/share/man/man1/pdf2dsc.1
/usr/share/man/man1/gsnd.1
/usr/share/man/man1/gslp.1
/usr/share/man/man1/gslj.1
/usr/share/man/man1/gsdj500.1
/usr/share/man/man1/gsdj.1
/usr/share/man/man1/gsbj.1
/usr/share/man/man1/gs.1
/usr/share/man/man1/eps2eps.1
/usr/share/man/man1/dvipdf.1
/usr/share/man/man1/
/usr/share/man/de/man1/ps2ps.1
/usr/share/man/de/man1/ps2pdf14.1
/usr/share/man/de/man1/ps2pdf13.1
/usr/share/man/de/man1/ps2pdf12.1
/usr/share/man/de/man1/ps2pdf.1
/usr/share/man/de/man1/ps2ascii.1
/usr/share/man/de/man1/printafm.1
/usr/share/man/de/man1/pdf2ps.1
/usr/share/man/de/man1/pdf2dsc.1
/usr/share/man/de/man1/gsnd.1
/usr/share/man/de/man1/eps2eps.1
/usr/share/man/de/man1/dvipdf.1
/usr/share/man/de/man1/
/usr/share/man/de/
/usr/share/man/
/usr/share/ghostscript/9.52/lib/zeroline.ps
/usr/share/ghostscript/9.52/lib/winmaps.ps
/usr/share/ghostscript/9.52/lib/viewps2a.ps
/usr/share/ghostscript/9.52/lib/viewpcx.ps
/usr/share/ghostscript/9.52/lib/viewpbm.ps
/usr/share/ghostscript/9.52/lib/viewmiff.ps
/usr/share/ghostscript/9.52/lib/viewjpeg.ps
/usr/share/ghostscript/9.52/lib/viewgif.ps
/usr/share/ghostscript/9.52/lib/viewcmyk.ps
/usr/share/ghostscript/9.52/lib/uninfo.ps
/usr/share/ghostscript/9.52/lib/traceop.ps
/usr/share/ghostscript/9.52/lib/traceimg.ps
/usr/share/ghostscript/9.52/lib/stocht.ps
/usr/share/ghostscript/9.52/lib/stcolor.ps
/usr/share/ghostscript/9.52/lib/stcinfo.ps
/usr/share/ghostscript/9.52/lib/stcany_h.upp
/usr/share/ghostscript/9.52/lib/stcany.upp
/usr/share/ghostscript/9.52/lib/stc_l.upp
/usr/share/ghostscript/9.52/lib/stc_h.upp
/usr/share/ghostscript/9.52/lib/stc800pl.upp
/usr/share/ghostscript/9.52/lib/stc800p.upp
/usr/share/ghostscript/9.52/lib/stc800ih.upp
/usr/share/ghostscript/9.52/lib/stc740ih.upp
/usr/share/ghostscript/9.52/lib/stc640p.upp
/usr/share/ghostscript/9.52/lib/stc600pl.upp
/usr/share/ghostscript/9.52/lib/stc600p.upp
/usr/share/ghostscript/9.52/lib/stc600ih.upp
/usr/share/ghostscript/9.52/lib/stc500ph.upp
/usr/share/ghostscript/9.52/lib/stc500p.upp
/usr/share/ghostscript/9.52/lib/stc300bm.upp
/usr/share/ghostscript/9.52/lib/stc300bl.upp
/usr/share/ghostscript/9.52/lib/stc300.upp
/usr/share/ghostscript/9.52/lib/stc2s_h.upp
/usr/share/ghostscript/9.52/lib/stc2_h.upp
/usr/share/ghostscript/9.52/lib/stc200_h.upp
/usr/share/ghostscript/9.52/lib/stc2.upp
/usr/share/ghostscript/9.52/lib/stc1520h.upp
/usr/share/ghostscript/9.52/lib/stc.upp
/usr/share/ghostscript/9.52/lib/st640plg.upp
/usr/share/ghostscript/9.52/lib/st640pl.upp
/usr/share/ghostscript/9.52/lib/st640pg.upp
/usr/share/ghostscript/9.52/lib/st640p.upp
/usr/share/ghostscript/9.52/lib/st640ihg.upp
/usr/share/ghostscript/9.52/lib/st640ih.upp
/usr/share/ghostscript/9.52/lib/sipixa6.upp
/usr/share/ghostscript/9.52/lib/sharp.upp
/usr/share/ghostscript/9.52/lib/s400b1.upp
/usr/share/ghostscript/9.52/lib/s400a1.upp
/usr/share/ghostscript/9.52/lib/rollconv.ps
/usr/share/ghostscript/9.52/lib/ras8m.upp
/usr/share/ghostscript/9.52/lib/ras4.upp
/usr/share/ghostscript/9.52/lib/ras32.upp
/usr/share/ghostscript/9.52/lib/ras3.upp
/usr/share/ghostscript/9.52/lib/ras24.upp
/usr/share/ghostscript/9.52/lib/ras1.upp
/usr/share/ghostscript/9.52/lib/ps2epsi.ps
/usr/share/ghostscript/9.52/lib/ps2ai.ps
/usr/share/ghostscript/9.52/lib/printafm.ps
/usr/share/ghostscript/9.52/lib/prfont.ps
/usr/share/ghostscript/9.52/lib/pphs.ps
/usr/share/ghostscript/9.52/lib/ppath.ps
/usr/share/ghostscript/9.52/lib/pfbtopfa.ps
/usr/share/ghostscript/9.52/lib/pf2afm.ps
/usr/share/ghostscript/9.52/lib/pdf_info.ps
/usr/share/ghostscript/9.52/lib/pdf2dsc.ps
/usr/share/ghostscript/9.52/lib/necp2x6.upp
/usr/share/ghostscript/9.52/lib/necp2x.upp
/usr/share/ghostscript/9.52/lib/mkcidfm.ps
/usr/share/ghostscript/9.52/lib/lines.ps
/usr/share/ghostscript/9.52/lib/landscap.ps
/usr/share/ghostscript/9.52/lib/jispaper.ps
/usr/share/ghostscript/9.52/lib/image-qa.ps
/usr/share/ghostscript/9.52/lib/ht_ccsto.ps
/usr/share/ghostscript/9.52/lib/gsnup.ps
/usr/share/ghostscript/9.52/lib/gslp.ps
/usr/share/ghostscript/9.52/lib/gs_wl5_e.ps
/usr/share/ghostscript/9.52/lib/gs_wl2_e.ps
/usr/share/ghostscript/9.52/lib/gs_wl1_e.ps
/usr/share/ghostscript/9.52/lib/gs_t_m.xbm
/usr/share/ghostscript/9.52/lib/gs_t.xpm
/usr/share/ghostscript/9.52/lib/gs_t.xbm
/usr/share/ghostscript/9.52/lib/gs_s_m.xbm
/usr/share/ghostscript/9.52/lib/gs_s.xpm
/usr/share/ghostscript/9.52/lib/gs_s.xbm
/usr/share/ghostscript/9.52/lib/gs_m_m.xbm
/usr/share/ghostscript/9.52/lib/gs_m.xpm
/usr/share/ghostscript/9.52/lib/gs_m.xbm
/usr/share/ghostscript/9.52/lib/gs_lgx_e.ps
/usr/share/ghostscript/9.52/lib/gs_lgo_e.ps
/usr/share/ghostscript/9.52/lib/gs_l_m.xbm
/usr/share/ghostscript/9.52/lib/gs_l.xpm
/usr/share/ghostscript/9.52/lib/gs_l.xbm
/usr/share/ghostscript/9.52/lib/gs_ksb_e.ps
/usr/share/ghostscript/9.52/lib/gs_kanji.ps
/usr/share/ghostscript/9.52/lib/gs_il2_e.ps
/usr/share/ghostscript/9.52/lib/gs_ce_e.ps
/usr/share/ghostscript/9.52/lib/ghostpdf.ppd
/usr/share/ghostscript/9.52/lib/font2pcl.ps
/usr/share/ghostscript/9.52/lib/escp_24.src
/usr/share/ghostscript/9.52/lib/docie.ps
/usr/share/ghostscript/9.52/lib/dnj750m.upp
/usr/share/ghostscript/9.52/lib/dnj750c.upp
/usr/share/ghostscript/9.52/lib/dmp_site.ps
/usr/share/ghostscript/9.52/lib/dmp_init.ps
/usr/share/ghostscript/9.52/lib/cid2code.ps
/usr/share/ghostscript/9.52/lib/cdj690ec.upp
/usr/share/ghostscript/9.52/lib/cdj690.upp
/usr/share/ghostscript/9.52/lib/cdj550.upp
/usr/share/ghostscript/9.52/lib/cbjc800.ppd
/usr/share/ghostscript/9.52/lib/cbjc600.ppd
/usr/share/ghostscript/9.52/lib/caption.ps
/usr/share/ghostscript/9.52/lib/bjc610b8.upp
/usr/share/ghostscript/9.52/lib/bjc610b7.upp
/usr/share/ghostscript/9.52/lib/bjc610b6.upp
/usr/share/ghostscript/9.52/lib/bjc610b4.upp
/usr/share/ghostscript/9.52/lib/bjc610b3.upp
/usr/share/ghostscript/9.52/lib/bjc610b2.upp
/usr/share/ghostscript/9.52/lib/bjc610b1.upp
/usr/share/ghostscript/9.52/lib/bjc610a8.upp
/usr/share/ghostscript/9.52/lib/bjc610a7.upp
/usr/share/ghostscript/9.52/lib/bjc610a6.upp
/usr/share/ghostscript/9.52/lib/bjc610a5.upp
/usr/share/ghostscript/9.52/lib/bjc610a4.upp
/usr/share/ghostscript/9.52/lib/bjc610a3.upp
/usr/share/ghostscript/9.52/lib/bjc610a2.upp
/usr/share/ghostscript/9.52/lib/bjc610a1.upp
/usr/share/ghostscript/9.52/lib/bjc610a0.upp
/usr/share/ghostscript/9.52/lib/bjc6000b1.upp
/usr/share/ghostscript/9.52/lib/bjc6000a1.upp
/usr/share/ghostscript/9.52/lib/bj8ts06n.upp
/usr/share/ghostscript/9.52/lib/bj8pp12f.upp
/usr/share/ghostscript/9.52/lib/bj8pa06n.upp
/usr/share/ghostscript/9.52/lib/bj8oh06n.upp
/usr/share/ghostscript/9.52/lib/bj8hg12f.upp
/usr/share/ghostscript/9.52/lib/bj8gc12f.upp
/usr/share/ghostscript/9.52/lib/bj8.rpd
/usr/share/ghostscript/9.52/lib/align.ps
/usr/share/ghostscript/9.52/lib/acctest.ps
/usr/share/ghostscript/9.52/lib/Stp870pl.upp
/usr/share/ghostscript/9.52/lib/Stp870p.upp
/usr/share/ghostscript/9.52/lib/Stp720pl.upp
/usr/share/ghostscript/9.52/lib/Stp720p.upp
/usr/share/ghostscript/9.52/lib/Stc777pl.upp
/usr/share/ghostscript/9.52/lib/Stc777p.upp
/usr/share/ghostscript/9.52/lib/Stc760pl.upp
/usr/share/ghostscript/9.52/lib/Stc760p.upp
/usr/share/ghostscript/9.52/lib/Stc740pl.upp
/usr/share/ghostscript/9.52/lib/Stc740p.upp
/usr/share/ghostscript/9.52/lib/Stc680pl.upp
/usr/share/ghostscript/9.52/lib/Stc680p.upp
/usr/share/ghostscript/9.52/lib/Stc670pl.upp
/usr/share/ghostscript/9.52/lib/Stc670p.upp
/usr/share/ghostscript/9.52/lib/PM820pl.upp
/usr/share/ghostscript/9.52/lib/PM820p.upp
/usr/share/ghostscript/9.52/lib/PM760pl.upp
/usr/share/ghostscript/9.52/lib/PM760p.upp
/usr/share/ghostscript/9.52/lib/PDFX_def.ps
/usr/share/ghostscript/9.52/lib/PDFA_def.ps
/usr/share/ghostscript/9.52/lib/
/usr/share/ghostscript/9.52/
/usr/share/ghostscript/
/usr/share/doc/ghostscript/9.52/thirdparty.htm
/usr/share/doc/ghostscript/9.52/subclass.htm
/usr/share/doc/ghostscript/9.52/style.css
/usr/share/doc/ghostscript/9.52/sample_downscale_device.htm
/usr/share/doc/ghostscript/9.52/pscet_status.txt
/usr/share/doc/ghostscript/9.52/index.js
/usr/share/doc/ghostscript/9.52/index.html
/usr/share/doc/ghostscript/9.52/images/x-light.png
/usr/share/doc/ghostscript/9.52/images/hamburger-light.png
/usr/share/doc/ghostscript/9.52/images/ghostscript_logo.png
/usr/share/doc/ghostscript/9.52/images/favicon.png
/usr/share/doc/ghostscript/9.52/images/Artifex_logo.png
/usr/share/doc/ghostscript/9.52/images/
/usr/share/doc/ghostscript/9.52/gs-style.css
/usr/share/doc/ghostscript/9.52/gdevds32.c
/usr/share/doc/ghostscript/9.52/WhatIsGS.htm
/usr/share/doc/ghostscript/9.52/VectorDevices.htm
/usr/share/doc/ghostscript/9.52/Use.htm
/usr/share/doc/ghostscript/9.52/Unix-lpr.htm
/usr/share/doc/ghostscript/9.52/Source.htm
/usr/share/doc/ghostscript/9.52/SavedPages.htm
/usr/share/doc/ghostscript/9.52/Release.htm
/usr/share/doc/ghostscript/9.52/Readme.htm
/usr/share/doc/ghostscript/9.52/Psfiles.htm
/usr/share/doc/ghostscript/9.52/Ps2epsi.htm
/usr/share/doc/ghostscript/9.52/Ps-style.htm
/usr/share/doc/ghostscript/9.52/News.htm
/usr/share/doc/ghostscript/9.52/Make.htm
/usr/share/doc/ghostscript/9.52/Lib.htm
/usr/share/doc/ghostscript/9.52/Language.htm
/usr/share/doc/ghostscript/9.52/Install.htm
/usr/share/doc/ghostscript/9.52/History9.htm
/usr/share/doc/ghostscript/9.52/GS9_Color_Management.pdf
/usr/share/doc/ghostscript/9.52/Fonts.htm
/usr/share/doc/ghostscript/9.52/Drivers.htm
/usr/share/doc/ghostscript/9.52/Devices.htm
/usr/share/doc/ghostscript/9.52/Develop.htm
/usr/share/doc/ghostscript/9.52/Deprecated.htm
/usr/share/doc/ghostscript/9.52/DLL.htm
/usr/share/doc/ghostscript/9.52/Commprod.htm
/usr/share/doc/ghostscript/9.52/COPYING
/usr/share/doc/ghostscript/9.52/C-style.htm
/usr/share/doc/ghostscript/9.52/API.htm
/usr/share/doc/ghostscript/9.52/
/usr/share/doc/ghostscript/
/usr/share/doc/
/usr/share/
/usr/lib/libgs.so.9.52
/usr/lib/libgs.so.9
/usr/lib/libgs.so
/usr/lib/
/usr/include/ghostscript/ierrors.h
/usr/include/ghostscript/iapi.h
/usr/include/ghostscript/gserrors.h
/usr/include/ghostscript/gdevdsp.h
/usr/include/ghostscript/
/usr/include/
/usr/bin/unix-lpr.sh
/usr/bin/ps2ps2
/usr/bin/ps2ps
/usr/bin/ps2pdfwr
/usr/bin/ps2pdf14
/usr/bin/ps2pdf13
/usr/bin/ps2pdf12
/usr/bin/ps2pdf
/usr/bin/ps2epsi
/usr/bin/ps2ascii
/usr/bin/printafm
/usr/bin/pphs
/usr/bin/pfbtopfa
/usr/bin/pf2afm
/usr/bin/pdf2ps
/usr/bin/pdf2dsc
/usr/bin/lprsetup.sh
/usr/bin/gsx
/usr/bin/gsnd
/usr/bin/gslp
/usr/bin/gslj
/usr/bin/gsdj500
/usr/bin/gsdj
/usr/bin/gsc
/usr/bin/gsbj
/usr/bin/gs
/usr/bin/eps2eps
/usr/bin/dvipdf
/usr/bin/
/usr/
```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify @dylanaraps if I can no longer maintain this package.

## Remarks

It's needed for `cups-filters`, but I'm still not sure it's needed for a lot of users. Besides `cups`, I use it to compress pdf files, so I find it convenient to have it. There is at the moment no dependencies. Without dependencies it compiles and can do what I want. I can add other dependencies if needed.

### CODE REVIEW

**Comment by dylanaraps** [comment]
The depends file can be removed if it's empty. :+1:

**Comment by Vouivre** [comment]
I see now, time to read 1206!

Change done!

**Comment by Vouivre** [comment]
Hhhmm, don't merge this PR. Something doesn't work. I'm searching the problem.

**Comment by Vouivre** [comment]
Now it's possible to print... it was the idea at the beginning :smile: !

**Pull request merged**
