### PR TITLE
sinit: ubase getty requires absolute path to tty

### PR DESCRIPTION
**Pull request by ioraff**

### CODE REVIEW

**Comment by dylanaraps** [comment]
@cemkeylan

**Comment by cemkeylan** [comment]
That's correct, I don't know how I missed that, I am using ubase getty. I was thinking that this was a commit wanting to remove the absolute path, until I saw that I didn't add it to begin with.

@dylanaraps I can push my own PR to keep the maintainer name on myself, or you can confirm this PR, as it fixes the issue.

**Comment by dylanaraps** [comment]
Send a pull request as you're the maintainer. =P

**Comment by dylanaraps** [comment]
Fixed

**Pull request closed without merging**
