### PR TITLE
sdl2: build fails with dash fix 

### LINKED ISSUE #872: sdl2: Cannot build with dash
sdl2 cannot build when /usr/bin/sh is set to dash (`kiss a dash /usr/bin/sh`)

This issue is already reported upstream at https://bugzilla.libsdl.org/show_bug.cgi?id=4261, but a workaround (like forcing busybox sh) or warning could be nice.

### PR DESCRIPTION
**Pull request by sdsddsd1**
Should print a warning for #872 

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Fails in dash but works in busybox sh?

**Comment by sdsddsd1** [comment]
Yep. I build with busybox sh with no problems.

**Comment by dylanaraps** [comment]
I don't like this solution as it affects users with dash installed (but with something else as /bin/sh). Does `CONFIG_SHELL=/bin/sh ./configure \` work at all?

**Comment by sdsddsd1** [comment]
`CONFIG_SHELL= ./configure \` does work.
When busybox is /bin/sh I can make it fail. And when dash is /bin/sh I can make it succed.
We could modify the warning to only print when dash is /bin/sh but I have no nice idea how to query that.

**Comment by sdsddsd1** [comment]
I have found a way to query dash and put that in line with other kiss-tools.
```
#!/bin/sh -e

log() {
    printf '\033[31;1m->\033[m %s.\n' "$@"
}

die() {
    log "$@"
    exit 1
}

kiss l dash &&
kiss a | grep "dash /usr/bin/sh" ||
die "ERROR: sdl2 can not be build with dash. Please change /usr/bin/sh to something appropiate"

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
```

**Comment by dylanaraps** [comment]
This should be fixed now. Simply update dash.

**Pull request closed without merging**
