### PR TITLE
sc-im: -fcommon flag added to CFLAGS

### PR DESCRIPTION
**Pull request by Vouivre**
Package adopted (see https://github.com/kisslinux/community/issues/1460). 

`build` file modified by addind the flag `-fcommon` in `CFLAGS`.

### CODE REVIEW

**Comment by dylanaraps** [comment]
You still must modify the version file. :+1:

**Comment by Vouivre** [comment]
Ok, done! I understood that a change had to be done to adopt a package. When the package is fine, the file `version` can be changed. Why is it necessary to always change it to adpot a package ?

**Comment by dylanaraps** [comment]
Maintainer is based on latest commit to the version file.

**Comment by Vouivre** [comment]
Thank you!

**Pull request merged**
