### PR TITLE
w3m: change version to 0.5.3

### PR DESCRIPTION
**Pull request by trbednarzyk**
Please fill out the template.

Read: https://k1ss.org/style
Read: https://k1ss.org/guidestones

---

## Existing package

- [X] I am the maintainer of this package.

### CODE REVIEW

**Comment by trbednarzyk** [comment]
See #656.

**Comment by cemkeylan** [comment]
Oh, I'm sorry I missed this pull request. Since you are changing version numbers, you don't need to bump the release numbers, as this change will cause a rebuild once they are in the repositories.

**Comment by trbednarzyk** [comment]
There, I changed it back.

**Comment by dylanaraps** [comment]
Open a new PR to bump only the second field for libressl. :+1:

**Comment by trbednarzyk** [comment]
Just to be clear, do I still have to bump the second field even though this PR changed the first field?

**Comment by dylanaraps** [comment]
Only for the Libressl update (when it comes). More info here: #656

**Pull request merged**
