### PR TITLE
gdb: Bump to 10.1

### PR DESCRIPTION
**Pull request by Xeno-Hypster**
## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by Xeno-Hypster** [comment]
Forgot to update checksum, will repost pull request once done.

**Comment by Xeno-Hypster** [comment]
Re-opened, checksums for gdb have been updated.

**Comment by dylanaraps** [comment]
Username change?

**Comment by Xeno-Hypster** [comment]
Yeah, should have said that outright, used to be Necromantic-Ritual.

**Pull request merged**
