### PR TITLE
glib-networking: bump to 2.64.2

### PR DESCRIPTION
**Pull request by cemkeylan**
See #656

### CODE REVIEW

**Comment by cemkeylan** [comment]
I have set the release number back to 1, and updated the package.

**Comment by cemkeylan** [comment]
Manifest, as always,

```
/var/db/kiss/installed/glib-networking/version
/var/db/kiss/installed/glib-networking/sources
/var/db/kiss/installed/glib-networking/manifest
/var/db/kiss/installed/glib-networking/depends
/var/db/kiss/installed/glib-networking/checksums
/var/db/kiss/installed/glib-networking/build
/var/db/kiss/installed/glib-networking/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgiognutls.so
/usr/lib/gio/modules/
/usr/lib/gio/
/usr/lib/
/usr/
```

**Comment by dylanaraps** [comment]
Will merge this as it is an update. Send another PR with the bump for libressl. :+1:

**Comment by dylanaraps** [comment]
Will merge this as it is an update. Send another PR with the bump for libressl. :+1:

**Pull request merged**
