### PR TITLE
new package: compton 0.1.2

### PR DESCRIPTION
**Pull request by a-schaefers**
## Checklist

- [x] Latest upstream version.
- [x] I agree to maintain this package (**required**).
- [x] I agree to notify KISS if I can no longer maintain this package (**required**).

### CODE REVIEW

**Comment by dylanaraps** [comment]
Please open individual pull requests for these. :+1:

**Comment by a-schaefers** [comment]
I was running out of time, I'm back to my day job now, but I wanted to get these pushed up here as quick as I could, will try to get back to this soon though.

**Comment by dylanaraps** [comment]
Apologies for not reviewing any of your PRs yet, it's Christmas so I'm a little busy. I hope you understand. :)

**Comment by a-schaefers** [comment]
I understand. Go easy on me when you get around to them. Some of these were sloppy in the beginning, I am getting better as I move along and learn best practices here. Happy Christmas

**Pull request closed without merging**
