### PR TITLE
glm: new package at 0.9.9.7

### PR DESCRIPTION
**Pull request by dm9pZCAq**
## Description of package
OpenGL Mathematics (GLM) is a header only C++ mathematics library for graphics software based on the OpenGL 

## Installed manifest of package
```
/var/db/kiss/installed/glm/version
/var/db/kiss/installed/glm/sources
/var/db/kiss/installed/glm/manifest
/var/db/kiss/installed/glm/files/glm.pc
/var/db/kiss/installed/glm/files/
/var/db/kiss/installed/glm/checksums
/var/db/kiss/installed/glm/build
/var/db/kiss/installed/glm/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/pkgconfig/glm.pc
/usr/share/pkgconfig/
/usr/share/
/usr/include/glm/vector_relational.hpp
/usr/include/glm/vec4.hpp
/usr/include/glm/vec3.hpp
/usr/include/glm/vec2.hpp
/usr/include/glm/trigonometric.hpp
/usr/include/glm/simd/vector_relational.h
/usr/include/glm/simd/trigonometric.h
/usr/include/glm/simd/platform.h
/usr/include/glm/simd/packing.h
/usr/include/glm/simd/neon.h
/usr/include/glm/simd/matrix.h
/usr/include/glm/simd/integer.h
/usr/include/glm/simd/geometric.h
/usr/include/glm/simd/exponential.h
/usr/include/glm/simd/common.h
/usr/include/glm/simd/
/usr/include/glm/packing.hpp
/usr/include/glm/matrix.hpp
/usr/include/glm/mat4x4.hpp
/usr/include/glm/mat4x3.hpp
/usr/include/glm/mat4x2.hpp
/usr/include/glm/mat3x4.hpp
/usr/include/glm/mat3x3.hpp
/usr/include/glm/mat3x2.hpp
/usr/include/glm/mat2x4.hpp
/usr/include/glm/mat2x3.hpp
/usr/include/glm/mat2x2.hpp
/usr/include/glm/integer.hpp
/usr/include/glm/gtx/wrap.inl
/usr/include/glm/gtx/wrap.hpp
/usr/include/glm/gtx/vector_query.inl
/usr/include/glm/gtx/vector_query.hpp
/usr/include/glm/gtx/vector_angle.inl
/usr/include/glm/gtx/vector_angle.hpp
/usr/include/glm/gtx/vec_swizzle.hpp
/usr/include/glm/gtx/type_trait.inl
/usr/include/glm/gtx/type_trait.hpp
/usr/include/glm/gtx/type_aligned.inl
/usr/include/glm/gtx/type_aligned.hpp
/usr/include/glm/gtx/transform2.inl
/usr/include/glm/gtx/transform2.hpp
/usr/include/glm/gtx/transform.inl
/usr/include/glm/gtx/transform.hpp
/usr/include/glm/gtx/texture.inl
/usr/include/glm/gtx/texture.hpp
/usr/include/glm/gtx/string_cast.inl
/usr/include/glm/gtx/string_cast.hpp
/usr/include/glm/gtx/std_based_type.inl
/usr/include/glm/gtx/std_based_type.hpp
/usr/include/glm/gtx/spline.inl
/usr/include/glm/gtx/spline.hpp
/usr/include/glm/gtx/scalar_relational.inl
/usr/include/glm/gtx/scalar_relational.hpp
/usr/include/glm/gtx/scalar_multiplication.hpp
/usr/include/glm/gtx/rotate_vector.inl
/usr/include/glm/gtx/rotate_vector.hpp
/usr/include/glm/gtx/rotate_normalized_axis.inl
/usr/include/glm/gtx/rotate_normalized_axis.hpp
/usr/include/glm/gtx/raw_data.inl
/usr/include/glm/gtx/raw_data.hpp
/usr/include/glm/gtx/range.hpp
/usr/include/glm/gtx/quaternion.inl
/usr/include/glm/gtx/quaternion.hpp
/usr/include/glm/gtx/projection.inl
/usr/include/glm/gtx/projection.hpp
/usr/include/glm/gtx/polar_coordinates.inl
/usr/include/glm/gtx/polar_coordinates.hpp
/usr/include/glm/gtx/perpendicular.inl
/usr/include/glm/gtx/perpendicular.hpp
/usr/include/glm/gtx/orthonormalize.inl
/usr/include/glm/gtx/orthonormalize.hpp
/usr/include/glm/gtx/optimum_pow.inl
/usr/include/glm/gtx/optimum_pow.hpp
/usr/include/glm/gtx/number_precision.inl
/usr/include/glm/gtx/number_precision.hpp
/usr/include/glm/gtx/normalize_dot.inl
/usr/include/glm/gtx/normalize_dot.hpp
/usr/include/glm/gtx/normal.inl
/usr/include/glm/gtx/normal.hpp
/usr/include/glm/gtx/norm.inl
/usr/include/glm/gtx/norm.hpp
/usr/include/glm/gtx/mixed_product.inl
/usr/include/glm/gtx/mixed_product.hpp
/usr/include/glm/gtx/matrix_transform_2d.inl
/usr/include/glm/gtx/matrix_transform_2d.hpp
/usr/include/glm/gtx/matrix_query.inl
/usr/include/glm/gtx/matrix_query.hpp
/usr/include/glm/gtx/matrix_operation.inl
/usr/include/glm/gtx/matrix_operation.hpp
/usr/include/glm/gtx/matrix_major_storage.inl
/usr/include/glm/gtx/matrix_major_storage.hpp
/usr/include/glm/gtx/matrix_interpolation.inl
/usr/include/glm/gtx/matrix_interpolation.hpp
/usr/include/glm/gtx/matrix_factorisation.inl
/usr/include/glm/gtx/matrix_factorisation.hpp
/usr/include/glm/gtx/matrix_decompose.inl
/usr/include/glm/gtx/matrix_decompose.hpp
/usr/include/glm/gtx/matrix_cross_product.inl
/usr/include/glm/gtx/matrix_cross_product.hpp
/usr/include/glm/gtx/log_base.inl
/usr/include/glm/gtx/log_base.hpp
/usr/include/glm/gtx/io.inl
/usr/include/glm/gtx/io.hpp
/usr/include/glm/gtx/intersect.inl
/usr/include/glm/gtx/intersect.hpp
/usr/include/glm/gtx/integer.inl
/usr/include/glm/gtx/integer.hpp
/usr/include/glm/gtx/hash.inl
/usr/include/glm/gtx/hash.hpp
/usr/include/glm/gtx/handed_coordinate_space.inl
/usr/include/glm/gtx/handed_coordinate_space.hpp
/usr/include/glm/gtx/gradient_paint.inl
/usr/include/glm/gtx/gradient_paint.hpp
/usr/include/glm/gtx/functions.inl
/usr/include/glm/gtx/functions.hpp
/usr/include/glm/gtx/float_notmalize.inl
/usr/include/glm/gtx/fast_trigonometry.inl
/usr/include/glm/gtx/fast_trigonometry.hpp
/usr/include/glm/gtx/fast_square_root.inl
/usr/include/glm/gtx/fast_square_root.hpp
/usr/include/glm/gtx/fast_exponential.inl
/usr/include/glm/gtx/fast_exponential.hpp
/usr/include/glm/gtx/exterior_product.inl
/usr/include/glm/gtx/exterior_product.hpp
/usr/include/glm/gtx/extended_min_max.inl
/usr/include/glm/gtx/extended_min_max.hpp
/usr/include/glm/gtx/extend.inl
/usr/include/glm/gtx/extend.hpp
/usr/include/glm/gtx/euler_angles.inl
/usr/include/glm/gtx/euler_angles.hpp
/usr/include/glm/gtx/easing.inl
/usr/include/glm/gtx/easing.hpp
/usr/include/glm/gtx/dual_quaternion.inl
/usr/include/glm/gtx/dual_quaternion.hpp
/usr/include/glm/gtx/component_wise.inl
/usr/include/glm/gtx/component_wise.hpp
/usr/include/glm/gtx/compatibility.inl
/usr/include/glm/gtx/compatibility.hpp
/usr/include/glm/gtx/common.inl
/usr/include/glm/gtx/common.hpp
/usr/include/glm/gtx/color_space_YCoCg.inl
/usr/include/glm/gtx/color_space_YCoCg.hpp
/usr/include/glm/gtx/color_space.inl
/usr/include/glm/gtx/color_space.hpp
/usr/include/glm/gtx/color_encoding.inl
/usr/include/glm/gtx/color_encoding.hpp
/usr/include/glm/gtx/closest_point.inl
/usr/include/glm/gtx/closest_point.hpp
/usr/include/glm/gtx/bit.inl
/usr/include/glm/gtx/bit.hpp
/usr/include/glm/gtx/associated_min_max.inl
/usr/include/glm/gtx/associated_min_max.hpp
/usr/include/glm/gtx/
/usr/include/glm/gtc/vec1.hpp
/usr/include/glm/gtc/ulp.inl
/usr/include/glm/gtc/ulp.hpp
/usr/include/glm/gtc/type_ptr.inl
/usr/include/glm/gtc/type_ptr.hpp
/usr/include/glm/gtc/type_precision.inl
/usr/include/glm/gtc/type_precision.hpp
/usr/include/glm/gtc/type_aligned.hpp
/usr/include/glm/gtc/round.inl
/usr/include/glm/gtc/round.hpp
/usr/include/glm/gtc/reciprocal.inl
/usr/include/glm/gtc/reciprocal.hpp
/usr/include/glm/gtc/random.inl
/usr/include/glm/gtc/random.hpp
/usr/include/glm/gtc/quaternion_simd.inl
/usr/include/glm/gtc/quaternion.inl
/usr/include/glm/gtc/quaternion.hpp
/usr/include/glm/gtc/packing.inl
/usr/include/glm/gtc/packing.hpp
/usr/include/glm/gtc/noise.inl
/usr/include/glm/gtc/noise.hpp
/usr/include/glm/gtc/matrix_transform.inl
/usr/include/glm/gtc/matrix_transform.hpp
/usr/include/glm/gtc/matrix_inverse.inl
/usr/include/glm/gtc/matrix_inverse.hpp
/usr/include/glm/gtc/matrix_integer.hpp
/usr/include/glm/gtc/matrix_access.inl
/usr/include/glm/gtc/matrix_access.hpp
/usr/include/glm/gtc/integer.inl
/usr/include/glm/gtc/integer.hpp
/usr/include/glm/gtc/epsilon.inl
/usr/include/glm/gtc/epsilon.hpp
/usr/include/glm/gtc/constants.inl
/usr/include/glm/gtc/constants.hpp
/usr/include/glm/gtc/color_space.inl
/usr/include/glm/gtc/color_space.hpp
/usr/include/glm/gtc/bitfield.inl
/usr/include/glm/gtc/bitfield.hpp
/usr/include/glm/gtc/
/usr/include/glm/glm.hpp
/usr/include/glm/geometric.hpp
/usr/include/glm/fwd.hpp
/usr/include/glm/ext/vector_ulp.inl
/usr/include/glm/ext/vector_ulp.hpp
/usr/include/glm/ext/vector_uint4_precision.hpp
/usr/include/glm/ext/vector_uint4.hpp
/usr/include/glm/ext/vector_uint3_precision.hpp
/usr/include/glm/ext/vector_uint3.hpp
/usr/include/glm/ext/vector_uint2_precision.hpp
/usr/include/glm/ext/vector_uint2.hpp
/usr/include/glm/ext/vector_uint1_precision.hpp
/usr/include/glm/ext/vector_uint1.hpp
/usr/include/glm/ext/vector_relational.inl
/usr/include/glm/ext/vector_relational.hpp
/usr/include/glm/ext/vector_integer.inl
/usr/include/glm/ext/vector_integer.hpp
/usr/include/glm/ext/vector_int4_precision.hpp
/usr/include/glm/ext/vector_int4.hpp
/usr/include/glm/ext/vector_int3_precision.hpp
/usr/include/glm/ext/vector_int3.hpp
/usr/include/glm/ext/vector_int2_precision.hpp
/usr/include/glm/ext/vector_int2.hpp
/usr/include/glm/ext/vector_int1_precision.hpp
/usr/include/glm/ext/vector_int1.hpp
/usr/include/glm/ext/vector_float4_precision.hpp
/usr/include/glm/ext/vector_float4.hpp
/usr/include/glm/ext/vector_float3_precision.hpp
/usr/include/glm/ext/vector_float3.hpp
/usr/include/glm/ext/vector_float2_precision.hpp
/usr/include/glm/ext/vector_float2.hpp
/usr/include/glm/ext/vector_float1_precision.hpp
/usr/include/glm/ext/vector_float1.hpp
/usr/include/glm/ext/vector_double4_precision.hpp
/usr/include/glm/ext/vector_double4.hpp
/usr/include/glm/ext/vector_double3_precision.hpp
/usr/include/glm/ext/vector_double3.hpp
/usr/include/glm/ext/vector_double2_precision.hpp
/usr/include/glm/ext/vector_double2.hpp
/usr/include/glm/ext/vector_double1_precision.hpp
/usr/include/glm/ext/vector_double1.hpp
/usr/include/glm/ext/vector_common.inl
/usr/include/glm/ext/vector_common.hpp
/usr/include/glm/ext/vector_bool4_precision.hpp
/usr/include/glm/ext/vector_bool4.hpp
/usr/include/glm/ext/vector_bool3_precision.hpp
/usr/include/glm/ext/vector_bool3.hpp
/usr/include/glm/ext/vector_bool2_precision.hpp
/usr/include/glm/ext/vector_bool2.hpp
/usr/include/glm/ext/vector_bool1_precision.hpp
/usr/include/glm/ext/vector_bool1.hpp
/usr/include/glm/ext/scalar_ulp.inl
/usr/include/glm/ext/scalar_ulp.hpp
/usr/include/glm/ext/scalar_uint_sized.hpp
/usr/include/glm/ext/scalar_relational.inl
/usr/include/glm/ext/scalar_relational.hpp
/usr/include/glm/ext/scalar_integer.inl
/usr/include/glm/ext/scalar_integer.hpp
/usr/include/glm/ext/scalar_int_sized.hpp
/usr/include/glm/ext/scalar_constants.inl
/usr/include/glm/ext/scalar_constants.hpp
/usr/include/glm/ext/scalar_common.inl
/usr/include/glm/ext/scalar_common.hpp
/usr/include/glm/ext/quaternion_trigonometric.inl
/usr/include/glm/ext/quaternion_trigonometric.hpp
/usr/include/glm/ext/quaternion_transform.inl
/usr/include/glm/ext/quaternion_transform.hpp
/usr/include/glm/ext/quaternion_relational.inl
/usr/include/glm/ext/quaternion_relational.hpp
/usr/include/glm/ext/quaternion_geometric.inl
/usr/include/glm/ext/quaternion_geometric.hpp
/usr/include/glm/ext/quaternion_float_precision.hpp
/usr/include/glm/ext/quaternion_float.hpp
/usr/include/glm/ext/quaternion_exponential.inl
/usr/include/glm/ext/quaternion_exponential.hpp
/usr/include/glm/ext/quaternion_double_precision.hpp
/usr/include/glm/ext/quaternion_double.hpp
/usr/include/glm/ext/quaternion_common_simd.inl
/usr/include/glm/ext/quaternion_common.inl
/usr/include/glm/ext/quaternion_common.hpp
/usr/include/glm/ext/matrix_transform.inl
/usr/include/glm/ext/matrix_transform.hpp
/usr/include/glm/ext/matrix_relational.inl
/usr/include/glm/ext/matrix_relational.hpp
/usr/include/glm/ext/matrix_projection.inl
/usr/include/glm/ext/matrix_projection.hpp
/usr/include/glm/ext/matrix_float4x4_precision.hpp
/usr/include/glm/ext/matrix_float4x4.hpp
/usr/include/glm/ext/matrix_float4x3_precision.hpp
/usr/include/glm/ext/matrix_float4x3.hpp
/usr/include/glm/ext/matrix_float4x2_precision.hpp
/usr/include/glm/ext/matrix_float4x2.hpp
/usr/include/glm/ext/matrix_float3x4_precision.hpp
/usr/include/glm/ext/matrix_float3x4.hpp
/usr/include/glm/ext/matrix_float3x3_precision.hpp
/usr/include/glm/ext/matrix_float3x3.hpp
/usr/include/glm/ext/matrix_float3x2_precision.hpp
/usr/include/glm/ext/matrix_float3x2.hpp
/usr/include/glm/ext/matrix_float2x4_precision.hpp
/usr/include/glm/ext/matrix_float2x4.hpp
/usr/include/glm/ext/matrix_float2x3_precision.hpp
/usr/include/glm/ext/matrix_float2x3.hpp
/usr/include/glm/ext/matrix_float2x2_precision.hpp
/usr/include/glm/ext/matrix_float2x2.hpp
/usr/include/glm/ext/matrix_double4x4_precision.hpp
/usr/include/glm/ext/matrix_double4x4.hpp
/usr/include/glm/ext/matrix_double4x3_precision.hpp
/usr/include/glm/ext/matrix_double4x3.hpp
/usr/include/glm/ext/matrix_double4x2_precision.hpp
/usr/include/glm/ext/matrix_double4x2.hpp
/usr/include/glm/ext/matrix_double3x4_precision.hpp
/usr/include/glm/ext/matrix_double3x4.hpp
/usr/include/glm/ext/matrix_double3x3_precision.hpp
/usr/include/glm/ext/matrix_double3x3.hpp
/usr/include/glm/ext/matrix_double3x2_precision.hpp
/usr/include/glm/ext/matrix_double3x2.hpp
/usr/include/glm/ext/matrix_double2x4_precision.hpp
/usr/include/glm/ext/matrix_double2x4.hpp
/usr/include/glm/ext/matrix_double2x3_precision.hpp
/usr/include/glm/ext/matrix_double2x3.hpp
/usr/include/glm/ext/matrix_double2x2_precision.hpp
/usr/include/glm/ext/matrix_double2x2.hpp
/usr/include/glm/ext/matrix_common.inl
/usr/include/glm/ext/matrix_common.hpp
/usr/include/glm/ext/matrix_clip_space.inl
/usr/include/glm/ext/matrix_clip_space.hpp
/usr/include/glm/ext/
/usr/include/glm/ext.hpp
/usr/include/glm/exponential.hpp
/usr/include/glm/detail/type_vec4_simd.inl
/usr/include/glm/detail/type_vec4.inl
/usr/include/glm/detail/type_vec4.hpp
/usr/include/glm/detail/type_vec3.inl
/usr/include/glm/detail/type_vec3.hpp
/usr/include/glm/detail/type_vec2.inl
/usr/include/glm/detail/type_vec2.hpp
/usr/include/glm/detail/type_vec1.inl
/usr/include/glm/detail/type_vec1.hpp
/usr/include/glm/detail/type_quat_simd.inl
/usr/include/glm/detail/type_quat.inl
/usr/include/glm/detail/type_quat.hpp
/usr/include/glm/detail/type_mat4x4_simd.inl
/usr/include/glm/detail/type_mat4x4.inl
/usr/include/glm/detail/type_mat4x4.hpp
/usr/include/glm/detail/type_mat4x3.inl
/usr/include/glm/detail/type_mat4x3.hpp
/usr/include/glm/detail/type_mat4x2.inl
/usr/include/glm/detail/type_mat4x2.hpp
/usr/include/glm/detail/type_mat3x4.inl
/usr/include/glm/detail/type_mat3x4.hpp
/usr/include/glm/detail/type_mat3x3.inl
/usr/include/glm/detail/type_mat3x3.hpp
/usr/include/glm/detail/type_mat3x2.inl
/usr/include/glm/detail/type_mat3x2.hpp
/usr/include/glm/detail/type_mat2x4.inl
/usr/include/glm/detail/type_mat2x4.hpp
/usr/include/glm/detail/type_mat2x3.inl
/usr/include/glm/detail/type_mat2x3.hpp
/usr/include/glm/detail/type_mat2x2.inl
/usr/include/glm/detail/type_mat2x2.hpp
/usr/include/glm/detail/type_half.inl
/usr/include/glm/detail/type_half.hpp
/usr/include/glm/detail/type_float.hpp
/usr/include/glm/detail/setup.hpp
/usr/include/glm/detail/qualifier.hpp
/usr/include/glm/detail/glm.cpp
/usr/include/glm/detail/func_vector_relational_simd.inl
/usr/include/glm/detail/func_vector_relational.inl
/usr/include/glm/detail/func_trigonometric_simd.inl
/usr/include/glm/detail/func_trigonometric.inl
/usr/include/glm/detail/func_packing_simd.inl
/usr/include/glm/detail/func_packing.inl
/usr/include/glm/detail/func_matrix_simd.inl
/usr/include/glm/detail/func_matrix.inl
/usr/include/glm/detail/func_integer_simd.inl
/usr/include/glm/detail/func_integer.inl
/usr/include/glm/detail/func_geometric_simd.inl
/usr/include/glm/detail/func_geometric.inl
/usr/include/glm/detail/func_exponential_simd.inl
/usr/include/glm/detail/func_exponential.inl
/usr/include/glm/detail/func_common_simd.inl
/usr/include/glm/detail/func_common.inl
/usr/include/glm/detail/compute_vector_relational.hpp
/usr/include/glm/detail/compute_common.hpp
/usr/include/glm/detail/_vectorize.hpp
/usr/include/glm/detail/_swizzle_func.hpp
/usr/include/glm/detail/_swizzle.hpp
/usr/include/glm/detail/_noise.hpp
/usr/include/glm/detail/_fixes.hpp
/usr/include/glm/detail/_features.hpp
/usr/include/glm/detail/
/usr/include/glm/common.hpp
/usr/include/glm/CMakeLists.txt
/usr/include/glm/
/usr/include/
/usr/

```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify @dylanaraps if I can no longer maintain this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Will any packages make use of this library? We typically only add libraries if another package will make use of them. :+1:

**Comment by dm9pZCAq** [comment]
Yes, `maim`(#669) require it
```
~/.cache/kiss/build-1220/maim/src/main.cpp:5:10: fatal error: 'glm/glm.hpp' file not found
#include <glm/glm.hpp>
```

After the merge, I will write to the maintainer of `maim` to add this library as a dependency

**Comment by dylanaraps** [comment]
This should only be a `make` dependency too from what I can see. :+1:

**Comment by onodera-punpun** [comment]
Eh, we actually `maim` depends on `slop`, which bundles glm: https://github.com/kisslinux/community/blob/master/community/slop/build

**Comment by dylanaraps** [comment]
Ah yes. I remember now. What prompted me to merge this was the fact that `maim` fails to build due to it being missing: 

```sh
[3/4] Building CXX object CMakeFiles/maim.dir/src/x.cpp.o
ninja: job failed: /usr/lib/ccache/bin/c++ -DMAIM_VERSION=\"v5.6.3\"  -march=native -pipe -O3 -fno-math-errno -O3 -DNDEBUG -std=c++11 -MD -MT CMakeFiles/maim.dir/src/main.cpp.o -MF CMakeFiles/maim.dir/src/main.cpp.o.d -o CMakeFiles/maim.dir/src/main.cpp.o -c ../src/main.cpp
../src/main.cpp:5:10: fatal error: glm/glm.hpp: No such file or directory
    5 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: job failed: /usr/lib/ccache/bin/c++ -DMAIM_VERSION=\"v5.6.3\"  -march=native -pipe -O3 -fno-math-errno -O3 -DNDEBUG -std=c++11 -MD -MT CMakeFiles/maim.dir/src/image.cpp.o -MF CMakeFiles/maim.dir/src/image.cpp.o.d -o CMakeFiles/maim.dir/src/image.cpp.o -c ../src/image.cpp
In file included from ../src/image.cpp:1:
../src/image.hpp:30:10: fatal error: glm/glm.hpp: No such file or directory
   30 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: job failed: /usr/lib/ccache/bin/c++ -DMAIM_VERSION=\"v5.6.3\"  -march=native -pipe -O3 -fno-math-errno -O3 -DNDEBUG -std=c++11 -MD -MT CMakeFiles/maim.dir/src/x.cpp.o -MF CMakeFiles/maim.dir/src/x.cpp.o.d -o CMakeFiles/maim.dir/src/x.cpp.o -c ../src/x.cpp
In file included from ../src/x.cpp:1:
../src/x.hpp:37:10: fatal error: glm/glm.hpp: No such file or directory
   37 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: subcommands failed
-> maim Build failed
```

Any ideas?

**Comment by dylanaraps** [comment]
I will revert this PR firstly. :+1:

**Comment by onodera-punpun** [comment]
Hm I am sorry, I am at home now and it seems like `maim` fails for me as well, we might have to keep `glm` as a seperate package and make both `slop` and `maim` depend on it then. If we do that you have to revert your revert :p

**Pull request merged**
