### PR TITLE
tor: bump to 0.4.2.6

### PR DESCRIPTION
**Pull request by IslandAlpha**
Read: https://k1ss.org/style
Read: https://k1ss.org/guidestones

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
One minor nitpick for the build file: https://github.com/kisslinux/community/blob/995459379b991e467f90a5b6b99d382459726e70/community/tor/build#L4

Remove the `\` from this line. :+1:

**Comment by IslandAlpha** [comment]
Would that warrant an increase of the package number? i.e. 1 -> 2?

**Comment by dylanaraps** [comment]
It would not as it's a cosmetic change. :+1:

**Comment by dylanaraps** [comment]
Thanks :+1:

**Pull request merged**
