### PR TITLE
tcc: new package at 0.9.27

### PR DESCRIPTION
**Pull request by IslandAlpha**
## Description of package

[Tiny C Compiler](https://bellard.org/tcc/)

Compared to gcc and clang, tcc is faster, simpler, and produces smaller binaries.

## Installed manifest of package

```
/var/db/kiss/installed/tcc/version
/var/db/kiss/installed/tcc/sources
/var/db/kiss/installed/tcc/manifest
/var/db/kiss/installed/tcc/depends
/var/db/kiss/installed/tcc/checksums
/var/db/kiss/installed/tcc/build
/var/db/kiss/installed/tcc/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man1/tcc.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/doc/tcc-doc.html
/usr/share/doc/
/usr/share/
/usr/lib/tcc/libtcc1.a
/usr/lib/tcc/include/varargs.h
/usr/lib/tcc/include/tcclib.h
/usr/lib/tcc/include/stddef.h
/usr/lib/tcc/include/stdbool.h
/usr/lib/tcc/include/stdarg.h
/usr/lib/tcc/include/float.h
/usr/lib/tcc/include/
/usr/lib/tcc/
/usr/lib/libtcc.a
/usr/lib/
/usr/include/libtcc.h
/usr/include/
/usr/bin/tcc
/usr/bin/
/usr/
```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify @dylanaraps if I can no longer maintain this package.

### CODE REVIEW

**Comment by IslandAlpha** [comment]
Now that I think of it, should I add `cc` and `c99` symlinks to tcc for the conflict system?

**Comment by dylanaraps** [comment]
I don't think so. What's compatibility like?

**Comment by IslandAlpha** [comment]
The [repo](https://savannah.nongnu.org/projects/tinycc) page says that:

> TCC not only supports ANSI C, but also most of the new ISO C99 standard and many GNUC extensions. 

"Most" is probably not good enough for a `c99` sym.

**Comment by dylanaraps** [comment]
We can always change this later on. :+1:

**Pull request merged**
