### PR TITLE
libcap: bump to 2.43 & fix for #1150

### PR DESCRIPTION
**Pull request by mmatongo**
## Installed manifest of package

```
/var/db/kiss/installed/libcap/version
/var/db/kiss/installed/libcap/sources
/var/db/kiss/installed/libcap/manifest
/var/db/kiss/installed/libcap/depends
/var/db/kiss/installed/libcap/checksums
/var/db/kiss/installed/libcap/build
/var/db/kiss/installed/libcap/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/setcap.8
/usr/share/man/man8/getpcaps.8
/usr/share/man/man8/getcap.8
/usr/share/man/man8/
/usr/share/man/man3/psx_syscall6.3
/usr/share/man/man3/psx_syscall3.3
/usr/share/man/man3/psx_syscall.3
/usr/share/man/man3/libpsx.3
/usr/share/man/man3/libcap.3
/usr/share/man/man3/capsetp.3
/usr/share/man/man3/capgetp.3
/usr/share/man/man3/cap_to_text.3
/usr/share/man/man3/cap_to_name.3
/usr/share/man/man3/cap_size.3
/usr/share/man/man3/cap_setuid.3
/usr/share/man/man3/cap_setgroups.3
/usr/share/man/man3/cap_set_secbits.3
/usr/share/man/man3/cap_set_proc.3
/usr/share/man/man3/cap_set_mode.3
/usr/share/man/man3/cap_set_flag.3
/usr/share/man/man3/cap_set_file.3
/usr/share/man/man3/cap_set_fd.3
/usr/share/man/man3/cap_mode_name.3
/usr/share/man/man3/cap_init.3
/usr/share/man/man3/cap_get_secbits.3
/usr/share/man/man3/cap_get_proc.3
/usr/share/man/man3/cap_get_pid.3
/usr/share/man/man3/cap_get_mode.3
/usr/share/man/man3/cap_get_flag.3
/usr/share/man/man3/cap_get_file.3
/usr/share/man/man3/cap_get_fd.3
/usr/share/man/man3/cap_get_bound.3
/usr/share/man/man3/cap_from_text.3
/usr/share/man/man3/cap_from_name.3
/usr/share/man/man3/cap_free.3
/usr/share/man/man3/cap_dup.3
/usr/share/man/man3/cap_drop_bound.3
/usr/share/man/man3/cap_copy_int.3
/usr/share/man/man3/cap_copy_ext.3
/usr/share/man/man3/cap_compare.3
/usr/share/man/man3/cap_clear_flag.3
/usr/share/man/man3/cap_clear.3
/usr/share/man/man3/
/usr/share/man/man1/capsh.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/
/usr/include/sys/psx_syscall.h
/usr/include/sys/capability.h
/usr/include/sys/
/usr/include/
/usr/
/sbin/setcap
/sbin/getpcaps
/sbin/getcap
/sbin/capsh
/sbin/
/pkgconfig/libpsx.pc
/pkgconfig/libcap.pc
/pkgconfig/
/libpsx.a
/libcap.so.2.42
/libcap.so.2
/libcap.so
/libcap.a
```

## Existing package

- [Y] I am the maintainer of this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Yeah. This manifest is wrong. `mk()` should be kept.

**Comment by mmatongo** [comment]
> Yeah. This manifest is wrong. `mk()` should be kept.

I noticed after I made the `pr`
my work around was

```
#!/bin/sh -e

make \
    prefix=/usr \
    sbindir=/usr/bin \
    lib=/usr/lib \
    pkgconfdir=/usr/lib/pkgconfig \
    RAISE_SETFCAP=no \
    INDENT=true \
    DESTDIR="$1"

make INDENT=true
make lib=lib DESTDIR="$1" install
```
This works just fine.

**Comment by dylanaraps** [comment]
You're calling `make` twice to build though? This seems odd.

**Comment by mmatongo** [comment]
the line `make INDENT=true` can be removed, I ignorantly thought it had to be called separately.
However `make lib=usr/lib DESTDIR="$1" install` is necessary to build successfully

**Comment by dylanaraps** [comment]
Send updated manifest?

**Comment by mmatongo** [comment]
The new manifest is as follows;
```
/var/db/kiss/installed/libcap/version
/var/db/kiss/installed/libcap/sources
/var/db/kiss/installed/libcap/manifest
/var/db/kiss/installed/libcap/checksums
/var/db/kiss/installed/libcap/build
/var/db/kiss/installed/libcap/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/setcap.8
/usr/share/man/man8/getpcaps.8
/usr/share/man/man8/getcap.8
/usr/share/man/man8/
/usr/share/man/man3/psx_syscall6.3
/usr/share/man/man3/psx_syscall3.3
/usr/share/man/man3/psx_syscall.3
/usr/share/man/man3/libpsx.3
/usr/share/man/man3/libcap.3
/usr/share/man/man3/capsetp.3
/usr/share/man/man3/capgetp.3
/usr/share/man/man3/cap_to_text.3
/usr/share/man/man3/cap_to_name.3
/usr/share/man/man3/cap_size.3
/usr/share/man/man3/cap_setuid.3
/usr/share/man/man3/cap_setgroups.3
/usr/share/man/man3/cap_set_secbits.3
/usr/share/man/man3/cap_set_proc.3
/usr/share/man/man3/cap_set_mode.3
/usr/share/man/man3/cap_set_flag.3
/usr/share/man/man3/cap_set_file.3
/usr/share/man/man3/cap_set_fd.3
/usr/share/man/man3/cap_mode_name.3
/usr/share/man/man3/cap_init.3
/usr/share/man/man3/cap_get_secbits.3
/usr/share/man/man3/cap_get_proc.3
/usr/share/man/man3/cap_get_pid.3
/usr/share/man/man3/cap_get_mode.3
/usr/share/man/man3/cap_get_flag.3
/usr/share/man/man3/cap_get_file.3
/usr/share/man/man3/cap_get_fd.3
/usr/share/man/man3/cap_get_bound.3
/usr/share/man/man3/cap_from_text.3
/usr/share/man/man3/cap_from_name.3
/usr/share/man/man3/cap_free.3
/usr/share/man/man3/cap_dup.3
/usr/share/man/man3/cap_drop_bound.3
/usr/share/man/man3/cap_copy_int.3
/usr/share/man/man3/cap_copy_ext.3
/usr/share/man/man3/cap_compare.3
/usr/share/man/man3/cap_clear_flag.3
/usr/share/man/man3/cap_clear.3
/usr/share/man/man3/
/usr/share/man/man1/capsh.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/
/usr/lib/pkgconfig/libpsx.pc
/usr/lib/pkgconfig/libcap.pc
/usr/lib/pkgconfig/
/usr/lib/libpsx.a
/usr/lib/libcap.so.2.43
/usr/lib/libcap.so.2
/usr/lib/libcap.so
/usr/lib/libcap.a
/usr/lib/
/usr/include/sys/psx_syscall.h
/usr/include/sys/capability.h
/usr/include/sys/
/usr/include/
/usr/
/sbin/setcap
/sbin/getpcaps
/sbin/getcap
/sbin/capsh
/sbin/
```

**Comment by mmatongo** [comment]
Looks and works alright on my end right now.

**Comment by dylanaraps** [comment]
It's still incorrect. All binaries should live in `/usr/bin`.

**Comment by mmatongo** [comment]
Ahh I see it, let me see if I can find a work around and if I can’t I go back to using the `mk` function

**Comment by mmatongo** [comment]
Figured out a solution;

```
install -Dm755 progs/setcap "$1/usr/bin/setcap"
install -Dm755 progs/getpcaps "$1/usr/bin/getpcaps"
install -Dm755 progs/getcap "$1/usr/bin/getcap"
install -Dm755 progs/capsh "$1/usr/bin/capsh"

rm -rf "$1/sbin"
```
`install` the binaries manually then delete the `sbin` dir.



This is the updated manifest file.
```
/var/db/kiss/installed/libcap/version
/var/db/kiss/installed/libcap/sources
/var/db/kiss/installed/libcap/manifest
/var/db/kiss/installed/libcap/checksums
/var/db/kiss/installed/libcap/build
/var/db/kiss/installed/libcap/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/setcap.8
/usr/share/man/man8/getpcaps.8
/usr/share/man/man8/getcap.8
/usr/share/man/man8/
/usr/share/man/man3/psx_syscall6.3
/usr/share/man/man3/psx_syscall3.3
/usr/share/man/man3/psx_syscall.3
/usr/share/man/man3/libpsx.3
/usr/share/man/man3/libcap.3
/usr/share/man/man3/capsetp.3
/usr/share/man/man3/capgetp.3
/usr/share/man/man3/cap_to_text.3
/usr/share/man/man3/cap_to_name.3
/usr/share/man/man3/cap_size.3
/usr/share/man/man3/cap_setuid.3
/usr/share/man/man3/cap_setgroups.3
/usr/share/man/man3/cap_set_secbits.3
/usr/share/man/man3/cap_set_proc.3
/usr/share/man/man3/cap_set_mode.3
/usr/share/man/man3/cap_set_flag.3
/usr/share/man/man3/cap_set_file.3
/usr/share/man/man3/cap_set_fd.3
/usr/share/man/man3/cap_mode_name.3
/usr/share/man/man3/cap_init.3
/usr/share/man/man3/cap_get_secbits.3
/usr/share/man/man3/cap_get_proc.3
/usr/share/man/man3/cap_get_pid.3
/usr/share/man/man3/cap_get_mode.3
/usr/share/man/man3/cap_get_flag.3
/usr/share/man/man3/cap_get_file.3
/usr/share/man/man3/cap_get_fd.3
/usr/share/man/man3/cap_get_bound.3
/usr/share/man/man3/cap_from_text.3
/usr/share/man/man3/cap_from_name.3
/usr/share/man/man3/cap_free.3
/usr/share/man/man3/cap_dup.3
/usr/share/man/man3/cap_drop_bound.3
/usr/share/man/man3/cap_copy_int.3
/usr/share/man/man3/cap_copy_ext.3
/usr/share/man/man3/cap_compare.3
/usr/share/man/man3/cap_clear_flag.3
/usr/share/man/man3/cap_clear.3
/usr/share/man/man3/
/usr/share/man/man1/capsh.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/
/usr/lib/pkgconfig/libpsx.pc
/usr/lib/pkgconfig/libcap.pc
/usr/lib/pkgconfig/
/usr/lib/libpsx.a
/usr/lib/libcap.so.2.43
/usr/lib/libcap.so.2
/usr/lib/libcap.so
/usr/lib/libcap.a
/usr/lib/
/usr/include/sys/psx_syscall.h
/usr/include/sys/capability.h
/usr/include/sys/
/usr/include/
/usr/bin/setcap
/usr/bin/getpcaps
/usr/bin/getcap
/usr/bin/capsh
/usr/bin/
/usr/
```

**Comment by dylanaraps** [comment]
Things worked with the `mk()` function did they not? Can we not simply add `INDENT=true` to the build file as-is?

**Comment by mmatongo** [comment]
> Things worked with the `mk()` function did they not? Can we not simply add `INDENT=true` to the build file as-is?

For the sake of simplicity, yes we can.

**Pull request closed without merging**
