### PR TITLE
harfbuzz-icu: bump to 2.7.0

### PR DESCRIPTION
**Pull request by cemkeylan**
It seems like harfbuzz will not be releasing tarballs with pre-made `configure` scripts. I have opted to `meson` instead of automake.

## Installed manifest of package

(`cat /var/db/kiss/installed/<pkg_name>/manifest`)

```
/var/db/kiss/installed/harfbuzz-icu/version
/var/db/kiss/installed/harfbuzz-icu/sources
/var/db/kiss/installed/harfbuzz-icu/manifest
/var/db/kiss/installed/harfbuzz-icu/depends
/var/db/kiss/installed/harfbuzz-icu/checksums
/var/db/kiss/installed/harfbuzz-icu/build
/var/db/kiss/installed/harfbuzz-icu/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/lib/pkgconfig/harfbuzz-icu.pc
/usr/lib/pkgconfig/
/usr/lib/libharfbuzz-icu.so.0.20700.0
/usr/lib/libharfbuzz-icu.so.0
/usr/lib/libharfbuzz-icu.so
/usr/lib/
/usr/include/harfbuzz/hb-icu.h
/usr/include/harfbuzz/
/usr/include/
/usr/
```

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
I must revert this until I can update `freetype-harfbuzz`. You should also check that yours correctly builds when `freetype-harfbuzz` is not installed.

**Comment by cemkeylan** [comment]
Thanks for the heads up! I didn't think how build system change could mess up so much. Your update does indeed build but it doesn't actually link harfbuzz to freetype unless it's pre-installed, which can cause issues. I have now fixed it completely and tested it without issues. Here is the build:

```sh
#!/bin/sh -e

build_freetype() (
    cd freetype

    CFLAGS="$CFLAGS -DDEFAULT_TT_INTERPRETER_VERSION=TT_INTERPRETER_VERSION_40" \
    ./configure \
        --prefix=/usr \
        --enable-freetype-config \
        --with-harfbuzz="$2"

    make
    make DESTDIR="$1" install
)

build_harfbuzz() (

    # Point Harfbuzz to the Freetype files.
    export CFLAGS="$CFLAGS -I$1/usr/include/freetype2"
    export CXXFLAGS="$CXXFLAGS -I$1/usr/include/freetype2"
    export LDFLAGS="$LDFLAGS -L$1/usr/lib"

    cd harfbuzz

    export DESTDIR="$1"
    meson \
        --prefix=/usr \
        -Dglib=enabled \
        -Dfreetype=enabled \
        -Ddefault_library=both \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        -Dpkg_config_path="$1/usr/lib/pkgconfig" \
        . output

    ninja -C output
    ninja -C output install
)

build_freetype "$1" no


build_harfbuzz "$1"

# Point Freetype to the Harfbuzz files.
export HARFBUZZ_CFLAGS="-I$PWD/harfbuzz/src"
export HARFBUZZ_LIBS="-L$PWD/harfbuzz/output/src -lharfbuzz"

build_freetype "$1" yes
```

**Comment by dylanaraps** [comment]
Applied your changes, thanks!

**Comment by cemkeylan** [comment]
Glad to help!

**Comment by dylanaraps** [comment]
More issues: https://github.com/kisslinux/repo/commit/05096e5a4dc6db5d202342f538d067d87ae7135e

I suggest another revert of this until the above is fixed.

**Pull request merged**
