### PR TITLE
mime-types: new package at 9

### PR DESCRIPTION
**Pull request by stefanfransen**
## Description of package
Provides a shared `/etc/mime.types` file
## Checklist

- [9] Latest upstream version.
- [x] I agree to maintain this package.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Not sure if obvious or not but the "I agree to maintain this package" is not optional (and by submitting this PR and the others you've agreed to maintain the 3~ packages).

What is the purpose of this package?  It looks to provide a single file? If this is essential it may be better in `baselayout`.

**Comment by stefanfransen** [comment]
Wasn't sure if the "I agree to maintain this package" is mandatory.
I'm fine with with maintaining the commited packages.

This package is a dependency of `mutt` / `neomutt`. Haven't got the build fully working yet.
`mime-types` provides a shared `/etc/mime.types` file used for attachment mime types.
Is it better to wait with PRs until I got all dependency packages + the main package working?

**Comment by dylanaraps** [comment]
>  Is it better to wait with PRs until I got all dependency packages + the main package working?

Yeah. 

Does this package have an upstream other than Gentoo?

**Comment by dylanaraps** [comment]
This file is now included in `baselayout`.

**Pull request closed without merging**
