### PR TITLE
new package: shadow 4.8.1

### PR DESCRIPTION
**Pull request by a-schaefers**
## Checklist

- [ ] Latest upstream version.
- [ ] I agree to maintain this package (**required**).
- [ ] I agree to notify KISS if I can no longer maintain this package (**required**).

### CODE REVIEW

**Comment by dylanaraps** [comment]
`libXslt` can be removed as a depend with `--disable-man`. The same may be doable for `webkitgtk` which is the only package that requires it.

**Comment by a-schaefers** [comment]
dep is fixed now to use libXslt

**Comment by dylanaraps** [comment]
Read my above comment.

**Comment by a-schaefers** [comment]
done

**Pull request merged**
