### PR TITLE
tcl: use system sqlite, symlink lib, install macros

### PR DESCRIPTION
**Pull request by ioraff**
also found no reason for using `make -j1`--installed just fine without it.

### CODE REVIEW

**Comment by dylanaraps** [comment]
@a-schaefers

**Comment by a-schaefers** [comment]
I have tested and approve of these tcl changes.

**Comment by a-schaefers** [comment]
Thank you @ioraff for your help.

**Comment by a-schaefers** [comment]
By the way @ioraff if you would like to adopt this package, let us know. :+1:

**Comment by a-schaefers** [comment]
@dylanaraps close this please.

**Pull request closed without merging**
