### PR TITLE
new package: nawk 20180827

### PR DESCRIPTION
**Pull request by a-schaefers**
## Description of package
one true awk
## Checklist

- [x] Latest upstream version.
- [x] I agree to maintain this package (**required**).
- [x] I agree to notify KISS if I can no longer maintain this package (**required**).

### CODE REVIEW

**Comment by dylanaraps** [comment]
Is this package really needed? I think it's better suited for a user repository which also includes a modified busybox package to exclude busybox awk so it can be installed to `/usr/bin`.

**Comment by a-schaefers** [comment]
awk is a classic and this is the original, preferred by a lot of old school devs and bsd guys. totally different than gawk. Should definitely be in our repo, especially considering how easy it is to compile and literally no maintenance at all to upkeep the build.

**Comment by a-schaefers** [comment]
We  don't want to modify the busybox base for the root user unless it is done for everybody, because too many variables come into play with maintaining packages / debugging failed builds, and also people's systems may break

**Comment by konimex** [comment]
FWIW the `awk` in many systems is packaged as `nawk`. See [Repology](https://repology.org/project/nawk/versions).

**Comment by a-schaefers** [comment]
nawk is fine by me

**Comment by dylanaraps** [comment]
Happy with `nawk` :+1:

**Comment by a-schaefers** [comment]
done

**Comment by dylanaraps** [comment]
The depends file can be removed. :+1:

**Comment by a-schaefers** [comment]
d584259 done

**Pull request merged**
